/**
 * Copyright 2009 KaChing Group Inc. Licensed under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law
 * or agreed to in writing, software distributed under the License is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package com.kaching.platform.common.values;


/**
 * Country names and alpha-2 codes as defined by
 * <a href="http://en.wikipedia.org/wiki/ISO_3166-1">ISO 3166-1</a>. This
 * enumeration was generated from the second edition of ISO 3166-1 and was
 * last updated on February, 22 2010 based on the ISO 3166-1 Newsletter VI-7.
 * Note that this enumeration also contains dependent territories and special
 * areas of geographical interest.
 */
public enum Country implements NumberedValue {

  AF(1, "Afghanistan"),
  AX(2, "\u00c5land Islands"),
  AL(3, "Albania"),
  DZ(4, "Algeria"),
  AS(5, "American Samoa"),
  AD(6, "Andorra"),
  AO(7, "Angola"),
  AI(8, "Anguilla"),
  AQ(9, "Antarctica"),
  AG(10, "Antigua and Barbuda"),
  AR(11, "Argentina"),
  AM(12, "Armenia"),
  AW(13, "Aruba"),
  AU(14, "Australia"),
  AT(15, "Austria"),
  AZ(16, "Azerbaijan"),
  BS(17, "Bahamas"),
  BH(18, "Bahrain"),
  BD(19, "Bangladesh"),
  BB(20, "Barbados"),
  BY(21, "Belarus"),
  BE(22, "Belgium"),
  BZ(23, "Belize"),
  BJ(24, "Benin"),
  BM(25, "Bermuda"),
  BT(26, "Bhutan"),
  BO(27, "Bolivia, Plurinational State of"),
  BA(28, "Bosnia and Herzegovina"),
  BW(29, "Botswana"),
  BV(30, "Bouvet Island"),
  BR(31, "Brazil"),
  IO(32, "British Indian Ocean Territory"),
  BN(33, "Brunei Darussalam"),
  BG(34, "Bulgaria"),
  BF(35, "Burkina Faso"),
  BI(36, "Burundi"),
  KH(37, "Cambodia"),
  CM(38, "Cameroon"),
  CA(39, "Canada"),
  CV(40, "Cape Verde"),
  KY(41, "Cayman Islands"),
  CF(42, "Central African Republic"),
  TD(43, "Chad"),
  CL(44, "Chile"),
  CN(45, "China"),
  CX(46, "Christmas Island"),
  CC(47, "Cocos (Keeling) Islands"),
  CO(48, "Colombia"),
  KM(49, "Comoros"),
  CG(50, "Congo"),
  CD(51, "Congo, the Democratic Republic of the"),
  CK(52, "Cook Islands"),
  CR(53, "Costa Rica"),
  CI(54, "C\u00f4te d'Ivoire"),
  HR(55, "Croatia"),
  CU(56, "Cuba"),
  CY(57, "Cyprus"),
  CZ(58, "Czech Republic"),
  DK(59, "Denmark"),
  DJ(60, "Djibouti"),
  DM(61, "Dominica"),
  DO(62, "Dominican Republic"),
  EC(63, "Ecuador"),
  EG(64, "Egypt"),
  SV(65, "El Salvador"),
  GQ(66, "Equatorial Guinea"),
  ER(67, "Eritrea"),
  EE(68, "Estonia"),
  ET(69, "Ethiopia"),
  FK(70, "Falkland Islands (Malvinas)"),
  FO(71, "Faroe Islands"),
  FJ(72, "Fiji"),
  FI(73, "Finland"),
  FR(74, "France"),
  GF(75, "French Guiana"),
  PF(76, "French Polynesia"),
  TF(77, "French Southern Territories"),
  GA(78, "Gabon"),
  GM(79, "Gambia"),
  GE(80, "Georgia"),
  DE(81, "Germany"),
  GH(82, "Ghana"),
  GI(83, "Gibraltar"),
  GR(84, "Greece"),
  GL(85, "Greenland"),
  GD(86, "Grenada"),
  GP(87, "Guadeloupe"),
  GU(88, "Guam"),
  GT(89, "Guatemala"),
  GG(90, "Guernsey"),
  GN(91, "Guinea"),
  GW(92, "Guinea-Bissau"),
  GY(93, "Guyana"),
  HT(94, "Haiti"),
  HM(95, "Heard Island and McDonald Islands"),
  VA(96, "Holy See (Vatican City State)"),
  HN(97, "Honduras"),
  HK(98, "Hong Kong"),
  HU(99, "Hungary"),
  IS(100, "Iceland"),
  IN(101, "India"),
  ID(102, "Indonesia"),
  IR(103, "Iran, Islamic Republic of"),
  IQ(104, "Iraq"),
  IE(105, "Ireland"),
  IM(106, "Isle of Man"),
  IL(107, "Israel"),
  IT(108, "Italy"),
  JM(109, "Jamaica"),
  JP(110, "Japan"),
  JE(111, "Jersey"),
  JO(112, "Jordan"),
  KZ(113, "Kazakhstan"),
  KE(114, "Kenya"),
  KI(115, "Kiribati"),
  KP(116, "Korea, Democratic People's Republic of"),
  KR(117, "Korea, Republic of"),
  KW(118, "Kuwait"),
  KG(119, "Kyrgyzstan"),
  LA(120, "Lao People's Democratic Republic"),
  LV(121, "Latvia"),
  LB(122, "Lebanon"),
  LS(123, "Lesotho"),
  LR(124, "Liberia"),
  LY(125, "Libyan Arab Jamahiriya"),
  LI(126, "Liechtenstein"),
  LT(127, "Lithuania"),
  LU(128, "Luxembourg"),
  MO(129, "Macao"),
  MK(130, "Macedonia, the former Yugoslav Republic of"),
  MG(131, "Madagascar"),
  MW(132, "Malawi"),
  MY(133, "Malaysia"),
  MV(134, "Maldives"),
  ML(135, "Mali"),
  MT(136, "Malta"),
  MH(137, "Marshall Islands"),
  MQ(138, "Martinique"),
  MR(139, "Mauritania"),
  MU(140, "Mauritius"),
  YT(141, "Mayotte"),
  MX(142, "Mexico"),
  FM(143, "Micronesia, Federated States of"),
  MD(144, "Moldova, Republic of"),
  MC(145, "Monaco"),
  MN(146, "Mongolia"),
  ME(147, "Montenegro"),
  MS(148, "Montserrat"),
  MA(149, "Morocco"),
  MZ(150, "Mozambique"),
  MM(151, "Myanmar"),
  NA(152, "Namibia"),
  NR(153, "Nauru"),
  NP(154, "Nepal"),
  NL(155, "Netherlands"),
  AN(156, "Netherlands Antilles"),
  NC(157, "New Caledonia"),
  NZ(158, "New Zealand"),
  NI(159, "Nicaragua"),
  NE(160, "Niger"),
  NG(161, "Nigeria"),
  NU(162, "Niue"),
  NF(163, "Norfolk Island"),
  MP(164, "Northern Mariana Islands"),
  NO(165, "Norway"),
  OM(166, "Oman"),
  PK(167, "Pakistan"),
  PW(168, "Palau"),
  PS(169, "Palestinian Territory, Occupied"),
  PA(170, "Panama"),
  PG(171, "Papua New Guinea"),
  PY(172, "Paraguay"),
  PE(173, "Peru"),
  PH(174, "Philippines"),
  PN(175, "Pitcairn"),
  PL(176, "Poland"),
  PT(177, "Portugal"),
  PR(178, "Puerto Rico"),
  QA(179, "Qatar"),
  RE(180, "R\u00e9union"),
  RO(181, "Romania"),
  RU(182, "Russian Federation"),
  RW(183, "Rwanda"),
  BL(184, "Saint Barth\u00e9lemy"),
  SH(185, "Saint Helena, Ascension and Tristan da Cunha"),
  KN(186, "Saint Kitts and Nevis"),
  LC(187, "Saint Lucia"),
  MF(188, "Saint Martin (French part)"),
  PM(189, "Saint Pierre and Miquelon"),
  VC(190, "Saint Vincent and the Grenadines"),
  WS(191, "Samoa"),
  SM(192, "San Marino"),
  ST(193, "Sao Tome and Principe"),
  SA(194, "Saudi Arabia"),
  SN(195, "Senegal"),
  RS(196, "Serbia"),
  SC(197, "Seychelles"),
  SL(198, "Sierra Leone"),
  SG(199, "Singapore"),
  SK(200, "Slovakia"),
  SI(201, "Slovenia"),
  SB(202, "Solomon Islands"),
  SO(203, "Somalia"),
  ZA(204, "South Africa"),
  GS(205, "South Georgia and the South Sandwich Islands"),
  ES(206, "Spain"),
  LK(207, "Sri Lanka"),
  SD(208, "Sudan"),
  SR(209, "Suriname"),
  SJ(210, "Svalbard and Jan Mayen"),
  SZ(211, "Swaziland"),
  SE(212, "Sweden"),
  CH(213, "Switzerland"),
  SY(214, "Syrian Arab Republic"),
  TW(215, "Taiwan, Province of China"),
  TJ(216, "Tajikistan"),
  TZ(217, "Tanzania, United Republic of"),
  TH(218, "Thailand"),
  TL(219, "Timor-Leste"),
  TG(220, "Togo"),
  TK(221, "Tokelau"),
  TO(222, "Tonga"),
  TT(223, "Trinidad and Tobago"),
  TN(224, "Tunisia"),
  TR(225, "Turkey"),
  TM(226, "Turkmenistan"),
  TC(227, "Turks and Caicos Islands"),
  TV(228, "Tuvalu"),
  UG(229, "Uganda"),
  UA(230, "Ukraine"),
  AE(231, "United Arab Emirates"),
  GB(232, "United Kingdom"),
  US(233, "United States"),
  UM(234, "United States Minor Outlying Islands"),
  UY(235, "Uruguay"),
  UZ(236, "Uzbekistan"),
  VU(237, "Vanuatu"),
  VE(238, "Venezuela, Bolivarian Republic of"),
  VN(239, "Viet Nam"),
  VG(240, "Virgin Islands, British"),
  VI(241, "Virgin Islands, U.S."),
  WF(242, "Wallis and Futuna"),
  EH(243, "Western Sahara"),
  YE(244, "Yemen"),
  ZM(245, "Zambia"),
  ZW(246, "Zimbabwe"),
  __(247, "Unknow");

  private final int number;
  private final String countryName;

  private Country(int number, String countryName) {
    this.number = number;
    this.countryName = countryName;
  }

  /**
   * Returns a consistently assigned number for the country.
   * @see NumberedValue
   */
  @Override
  public int getNumber() {
    return number;
  }

  /**
   * Returns the country name.
   */
  public String getCountryName() {
    return countryName;
  }

  /**
   * Returns the ISO 3166-1 alpha-2 code assigned to the country.
   */
  public String getAlpha2() {
    return name();
  }

}
